# cSpell:ignore darkmode
menu:
  Home: / || fas fa-home
  Projects: /projects/ || fas fa-code
  Archives: /archives/ || fas fa-archive
  Tags: /tags/ || fas fa-tags
  Categories: /categories/ || fas fa-folder-open
  About: /about/ || fas fa-user

# 全局背景相关
index_img: /img/bg.jpg.jpg
background: url(/img/bg.jpg.jpg)
background_dark: url(/img/bg.jpg.jpg)
background_style: "background-attachment: fixed; background-size: cover; background-repeat: no-repeat;"

subtitle:
  enable: true  
  sub:  
    - "In the realm of ones and zeros."
    - "Code is Law. Logic is Art."

# 功能开关
local_search:
  enable: true  
darkmode:
  enable: true  
  button: true  

# 头像配置
avatar:
  img: /img/avatar.jpg.jpg
  rounded: true
  opacity: 1
  zoom: true

# 1. 社交链接：这里必须先定义 github（注意全是小写，这是 key）
social:
  github: https://github.com/djdj-student || fab fa-github

# 2. Follow Me：这里是调用上面的 key
follow_me:
  enable: true
  # 重点：这里的 github 必须和上面 social 里的 github 名字一模一样
  github: true 


# CSS注入
inject:
  head:
    - <link rel="stylesheet" href="/css/custom.css">
  bottom: []
